#Server Configuration
server:
  port: 4000

#Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_ws?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
        ddl-auto: update
    show-sql: true
